#!/usr/bin/env bash
# BHNM APNs Middleware — Setup Wizard
# Generates .env from interactive prompts.
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo "┌──────────────────────────────────────────────┐"
echo "│   BHNM APNs Middleware — Setup Wizard         │"
echo "└──────────────────────────────────────────────┘"
echo ""

ask() {
    local prompt="$1" default="$2" result
    if [ -n "$default" ]; then
        read -rp "$prompt [$default]: " result
        echo "${result:-$default}"
    else
        read -rp "$prompt: " result
        echo "$result"
    fi
}

# ── APNs ───────────────────────────────────────────
echo -e "${CYAN}── APNs Configuration ────────────────────────────${NC}"
APNS_KEY_ID=$(ask   "APNs Key ID   (10 chars, from Apple Developer)" "")
APNS_TEAM_ID=$(ask  "APNs Team ID  (10 chars, from Apple Developer)" "")
APNS_BUNDLE_ID=$(ask "Bundle ID" "com.tstolt.benem")

# ── Private key ────────────────────────────────────
echo ""
echo -e "${CYAN}── APNs Private Key (.p8) ────────────────────────${NC}"
read -rp "Full path to your AuthKey_XXXXXX.p8 file: " P8_PATH
P8_PATH="${P8_PATH/#\~/$HOME}"
if [ ! -f "$P8_PATH" ]; then
    echo "Error: file not found: $P8_PATH"
    exit 1
fi
APNS_PRIVATE_KEY_B64=$(base64 -w 0 "$P8_PATH" 2>/dev/null || base64 "$P8_PATH")
echo -e "${GREEN}✓ Key loaded and encoded.${NC}"

# ── Domain ─────────────────────────────────────────
echo ""
echo -e "${CYAN}── Domain ────────────────────────────────────────${NC}"
DOMAIN=$(ask "Domain for this service" "bhnm-apns.example.com")

# ── Write .env ─────────────────────────────────────
cat > .env <<EOF
# BHNM APNs Middleware — generated by setup.sh $(date -u +"%Y-%m-%d %H:%M UTC")
# DO NOT COMMIT THIS FILE

# APNs
APNS_KEY_ID=$APNS_KEY_ID
APNS_TEAM_ID=$APNS_TEAM_ID
APNS_BUNDLE_ID=$APNS_BUNDLE_ID
APNS_PRIVATE_KEY_B64=$APNS_PRIVATE_KEY_B64

# Server
DOMAIN=$DOMAIN

# Authentication: each BHNM server uses its own unique webhook secret (per-device routing).
# Configure the secret in BHNM's webhook URL (?secret=YOUR_SECRET) and in BeNeM Settings.
# Generate a unique secret per server with: openssl rand -hex 32
EOF

echo ""
echo -e "${GREEN}✓ .env written.${NC}"
echo ""
echo "┌──────────────────────────────────────────────┐"
echo "│   Next steps                                  │"
echo "│                                               │"
echo "│  1. Add DNS A record:                         │"
echo "│     $DOMAIN → <this server IP>   │"
echo "│                                               │"
echo "│  2. Start the service:                        │"
echo "│     docker compose up -d                      │"
echo "│                                               │"
echo "│  3. Generate a secret per BHNM server:        │"
echo "│     openssl rand -hex 32                      │"
echo "│                                               │"
echo "│  4. Configure BHNM webhook URL:               │"
echo "│     https://$DOMAIN/webhook?secret=<secret>   │"
echo "│                                               │"
echo "│  5. In BeNeM Settings → BHNM Server:          │"
echo "│     Middleware URL: https://$DOMAIN │"
echo "│     Webhook Secret: <same secret>             │"
echo "└──────────────────────────────────────────────┘"
echo ""
